/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/UZOLCjuu9EO
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Rubik } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from '@/src/components/ui/input';
import { Button } from '@/src/components/ui/button';

export function StockSearch() {
  return (
    <div className='container mx-auto px-4 py-8'>
      <div className='mb-6 flex items-center'>
        <Input
          className='mr-4 flex-1 bg-white dark:bg-gray-950'
          placeholder='Search stocks...'
          type='text'
        />
        <Button className='shrink-0' variant='outline'>
          <ListIcon className='h-5 w-5' />
          <span className='sr-only'>Toggle view</span>
        </Button>
      </div>
      <div className='grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4' />
    </div>
  );
}

function ListIcon(props) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <line x1='8' x2='21' y1='6' y2='6' />
      <line x1='8' x2='21' y1='12' y2='12' />
      <line x1='8' x2='21' y1='18' y2='18' />
      <line x1='3' x2='3.01' y1='6' y2='6' />
      <line x1='3' x2='3.01' y1='12' y2='12' />
      <line x1='3' x2='3.01' y1='18' y2='18' />
    </svg>
  );
}
